name: DailyTask

on:
  # push:
  #   branches:
  #     - main
  # 东八区每天八点多运行
  schedule:
    - cron: "0 0 * * *"
  # 标星时运行
  watch:
    types: [started]

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # 这里必须是0, gitee 不允许 shallow push
          fetch-depth: 0

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.9.0

      - name: My-Tasks
        run: |
          # 设置Git
          if [ a${{ secrets.PUSH_EMAIL }} != a ]; then
            git config --local user.name ${{ github.actor }}
            git config --local user.email ${{ secrets.PUSH_EMAIL }}
          else
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions@github.com"
          fi
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          # 记录log
          date +"%Y-%m-%d %H:%M:%S.%N" >> Tasks.log

          # 推送
          git add .
          git commit -am "A commit a day keeps girlfriend away."
          git push origin main

